language: node_js

node_js:
  - '5.11'

install: ./travis/install.sh

before_script:
  - npm install -g gulp

script: ./travis/script.sh

cache:
  directories:
    - node_modules
    - bower_components
    - unit_tests/bower_components

env:
  - secure: "EOLSkOnWNqKODETqXwoRK+KbxyR11YCTi8kRX0+q21KQKaTqqt39UzSOoD0qlfKXPU+D23kvWSYWcGbHQw6DiVHtenVbn9ktik3lJkscXpJmNJmaregclSYJpaK7GC5vJU0av4Q0lDASxrqBv9FftrAEoC7fTfdoZgJ8t29huoU="

deploy:
  - provider: script
    script: ./travis/deploy.sh
    on:
      tags: true
    skip_cleanup: true
  - provider: script
    script: ./travis/deploy.sh
    on:
      branch: master
    skip_cleanup: true

